"""
Script to build GLOBAL_WORKFLOW_TOOLS_CATALOG.txt, GLOBAL_WORKFLOW_TOOLS_AI_MAPPING.txt,
and tools_catalog.json with all 1057 tools across 8 categories.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Category definition with list of tools
CAD_TOOLS = [
    ("AutoCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD LT", "LibreCAD", "https://github.com/LibreCAD/LibreCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD Civil 3D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD Map 3D", "QGIS", "https://github.com/qgis/QGIS", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD Plant 3D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD Electrical", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("AutoCAD Mechanical", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("AutoCAD Architecture", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Revit", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Inventor", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Fusion 360", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Forma", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk InfraWorks", "QGIS", "https://github.com/qgis/QGIS", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Navisworks", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk ReCap Pro", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Robot Structural Analysis", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Advance Steel", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk 3ds Max", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("SOLIDWORKS", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SOLIDWORKS Electrical", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("SOLIDWORKS Visualize", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Solid Edge", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("CATIA", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Siemens NX", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("PTC Creo", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Onshape", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("FreeCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("LibreCAD", "LibreCAD", "https://github.com/LibreCAD/LibreCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("QCAD", "LibreCAD", "https://github.com/LibreCAD/LibreCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("DraftSight", "LibreCAD", "https://github.com/LibreCAD/LibreCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BricsCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BricsCAD BIM", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("ZWCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("GstarCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("nanoCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("ARCHICAD", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Vectorworks Architect", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Chief Architect", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SketchUp", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("Rhino 3D", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("Grasshopper", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("OpenSCAD", "OpenSCAD", "https://github.com/openscad/openscad", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SolveSpace", "SolveSpace", "https://github.com/solvespace/solvespace", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Shapr3D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Plasticity", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("Alibre Design", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("TurboCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("IronCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("ANSYS SpaceClaim", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("DesignSpark Mechanical", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("KOMPAS-3D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("VariCAD", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley MicroStation", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley OpenBuildings Designer", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley OpenRoads Designer", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley OpenRail Designer", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley OpenBridge Modeler", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley STAAD.Pro", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bentley RAM Structural System", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Tekla Structures", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Tekla Structural Designer", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("ETABS", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SAP2000", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SAFE", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("RFEM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("RSTAB", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SCIA Engineer", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("ProtaStructure", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Allplan", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Edificius", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("MagiCAD", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("DDS-CAD", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Trimble Connect", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Revizto", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Solibri", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BIMcollab", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BIMvision", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BIMx", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Dalux", "IfcOpenShell", "https://github.com/IfcOpenShell/IfcOpenShell", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Bluebeam Revu", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("PointCab", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("CloudCompare", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Leica Cyclone 3DR", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Trimble RealWorks", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Geomagic Design X", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("PolyWorks Modeler", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("MeshLab", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk Meshmixer", "CloudCompare", "https://github.com/CloudCompare/CloudCompare", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Blender", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("Houdini", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Tinkercad", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("SelfCAD", "Blender", "https://github.com/blender/blender", "FreedomIntelligence/BlenderLLM", "https://huggingface.co/FreedomIntelligence/BlenderLLM"),
    ("BlocksCAD", "OpenSCAD", "https://github.com/openscad/openscad", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Mastercam", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SolidCAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Fusion 360 Manufacturing", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("hyperMILL", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Siemens NX CAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("GibbsCAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Edgecam", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk FeatureCAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk PowerMill", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("HSMWorks", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("SprutCAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("BobCAD-CAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("CAMWorks", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("OpenBuilds CAM", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("KiCad", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Autodesk EAGLE", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("Altium Designer", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("Cadence OrCAD", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("Cadence Allegro", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("Siemens Xpedition", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("PADS Professional", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("EasyEDA", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("CircuitMaker", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("DipTrace", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Proteus Design Suite", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("DesignSpark PCB", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("LibrePCB", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "Multilingual-Multimodal-NLP/IndustrialCoder", "https://huggingface.co/Multilingual-Multimodal-NLP/IndustrialCoder"),
    ("gEDA", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Fritzing", "KiCad", "https://github.com/KiCad/kicad-source-mirror", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Esri CityEngine", "QGIS", "https://github.com/qgis/QGIS", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Planner 5D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Floorplanner", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("Sweet Home 3D", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
    ("RoomSketcher", "FreeCAD", "https://github.com/FreeCAD/FreeCAD", "ADSKAILab/Zero-To-CAD-Qwen3-VL-2B", "https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B"),
]

print(f"Loaded {len(CAD_TOOLS)} CAD tools.")
